version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  producer:
    build: .
    command: python producer.py
    environment:
      - PYTHONUNBUFFERED=1    # <--- BUNU EKLİYORUZ (Logları anında gösterir)
    depends_on:
      - rabbitmq
    restart: always

  consumer:
    build: .
    command: python consumer.py
    environment:
      - PYTHONUNBUFFERED=1    # <--- BUNU EKLİYORUZ
    depends_on:
      - rabbitmq
    restart: always   

  server:
    build: .
    command: python server.py
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    restart: always   